"""empty message

Revision ID: a2032aee7391
Revises: 87dc74ca37fe
Create Date: 2020-05-18 17:32:13.400572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2032aee7391'
down_revision = '87dc74ca37fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.Text(length=10240), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=10240), nullable=True))
    op.drop_column('post', 'content')
    # ### end Alembic commands ###
